# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/albert/689-HW2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/albert/689-HW2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/albert/689-HW2/CMakeFiles /home/albert/689-HW2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/albert/689-HW2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named adduser

# Build rule for target.
adduser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adduser
.PHONY : adduser

# fast build rule for target.
adduser/fast:
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/build
.PHONY : adduser/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

src/Client.o: src/Client.cpp.o

.PHONY : src/Client.o

# target to build an object file
src/Client.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Client.cpp.o
.PHONY : src/Client.cpp.o

src/Client.i: src/Client.cpp.i

.PHONY : src/Client.i

# target to preprocess a source file
src/Client.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Client.cpp.i
.PHONY : src/Client.cpp.i

src/Client.s: src/Client.cpp.s

.PHONY : src/Client.s

# target to generate assembly for a file
src/Client.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Client.cpp.s
.PHONY : src/Client.cpp.s

src/CryptoEval.o: src/CryptoEval.cpp.o

.PHONY : src/CryptoEval.o

# target to build an object file
src/CryptoEval.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/CryptoEval.cpp.o
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/CryptoEval.cpp.o
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/CryptoEval.cpp.o
.PHONY : src/CryptoEval.cpp.o

src/CryptoEval.i: src/CryptoEval.cpp.i

.PHONY : src/CryptoEval.i

# target to preprocess a source file
src/CryptoEval.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/CryptoEval.cpp.i
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/CryptoEval.cpp.i
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/CryptoEval.cpp.i
.PHONY : src/CryptoEval.cpp.i

src/CryptoEval.s: src/CryptoEval.cpp.s

.PHONY : src/CryptoEval.s

# target to generate assembly for a file
src/CryptoEval.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/CryptoEval.cpp.s
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/CryptoEval.cpp.s
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/CryptoEval.cpp.s
.PHONY : src/CryptoEval.cpp.s

src/IP.o: src/IP.cpp.o

.PHONY : src/IP.o

# target to build an object file
src/IP.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/IP.cpp.o
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/IP.cpp.o
.PHONY : src/IP.cpp.o

src/IP.i: src/IP.cpp.i

.PHONY : src/IP.i

# target to preprocess a source file
src/IP.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/IP.cpp.i
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/IP.cpp.i
.PHONY : src/IP.cpp.i

src/IP.s: src/IP.cpp.s

.PHONY : src/IP.s

# target to generate assembly for a file
src/IP.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/IP.cpp.s
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/IP.cpp.s
.PHONY : src/IP.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Logger.cpp.o
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Logger.cpp.i
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Logger.cpp.s
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Server.o: src/Server.cpp.o

.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i

.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s

.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/Session.o: src/Session.cpp.o

.PHONY : src/Session.o

# target to build an object file
src/Session.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Session.cpp.o
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Session.cpp.o
.PHONY : src/Session.cpp.o

src/Session.i: src/Session.cpp.i

.PHONY : src/Session.i

# target to preprocess a source file
src/Session.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Session.cpp.i
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Session.cpp.i
.PHONY : src/Session.cpp.i

src/Session.s: src/Session.cpp.s

.PHONY : src/Session.s

# target to generate assembly for a file
src/Session.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Session.cpp.s
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Session.cpp.s
.PHONY : src/Session.cpp.s

src/User.o: src/User.cpp.o

.PHONY : src/User.o

# target to build an object file
src/User.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/User.cpp.o
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/User.cpp.o
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/User.cpp.o
.PHONY : src/User.cpp.o

src/User.i: src/User.cpp.i

.PHONY : src/User.i

# target to preprocess a source file
src/User.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/User.cpp.i
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/User.cpp.i
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/User.cpp.i
.PHONY : src/User.cpp.i

src/User.s: src/User.cpp.s

.PHONY : src/User.s

# target to generate assembly for a file
src/User.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/User.cpp.s
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/User.cpp.s
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/User.cpp.s
.PHONY : src/User.cpp.s

src/add_user_main.o: src/add_user_main.cpp.o

.PHONY : src/add_user_main.o

# target to build an object file
src/add_user_main.cpp.o:
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/add_user_main.cpp.o
.PHONY : src/add_user_main.cpp.o

src/add_user_main.i: src/add_user_main.cpp.i

.PHONY : src/add_user_main.i

# target to preprocess a source file
src/add_user_main.cpp.i:
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/add_user_main.cpp.i
.PHONY : src/add_user_main.cpp.i

src/add_user_main.s: src/add_user_main.cpp.s

.PHONY : src/add_user_main.s

# target to generate assembly for a file
src/add_user_main.cpp.s:
	$(MAKE) -f CMakeFiles/adduser.dir/build.make CMakeFiles/adduser.dir/src/add_user_main.cpp.s
.PHONY : src/add_user_main.cpp.s

src/client_main.o: src/client_main.cpp.o

.PHONY : src/client_main.o

# target to build an object file
src/client_main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/client_main.cpp.o
.PHONY : src/client_main.cpp.o

src/client_main.i: src/client_main.cpp.i

.PHONY : src/client_main.i

# target to preprocess a source file
src/client_main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/client_main.cpp.i
.PHONY : src/client_main.cpp.i

src/client_main.s: src/client_main.cpp.s

.PHONY : src/client_main.s

# target to generate assembly for a file
src/client_main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/client_main.cpp.s
.PHONY : src/client_main.cpp.s

src/server_main.o: src/server_main.cpp.o

.PHONY : src/server_main.o

# target to build an object file
src/server_main.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server_main.cpp.o
.PHONY : src/server_main.cpp.o

src/server_main.i: src/server_main.cpp.i

.PHONY : src/server_main.i

# target to preprocess a source file
src/server_main.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server_main.cpp.i
.PHONY : src/server_main.cpp.i

src/server_main.s: src/server_main.cpp.s

.PHONY : src/server_main.s

# target to generate assembly for a file
src/server_main.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server_main.cpp.s
.PHONY : src/server_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Server"
	@echo "... rebuild_cache"
	@echo "... adduser"
	@echo "... Client"
	@echo "... src/Client.o"
	@echo "... src/Client.i"
	@echo "... src/Client.s"
	@echo "... src/CryptoEval.o"
	@echo "... src/CryptoEval.i"
	@echo "... src/CryptoEval.s"
	@echo "... src/IP.o"
	@echo "... src/IP.i"
	@echo "... src/IP.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/Session.o"
	@echo "... src/Session.i"
	@echo "... src/Session.s"
	@echo "... src/User.o"
	@echo "... src/User.i"
	@echo "... src/User.s"
	@echo "... src/add_user_main.o"
	@echo "... src/add_user_main.i"
	@echo "... src/add_user_main.s"
	@echo "... src/client_main.o"
	@echo "... src/client_main.i"
	@echo "... src/client_main.s"
	@echo "... src/server_main.o"
	@echo "... src/server_main.i"
	@echo "... src/server_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

